In [27]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('bitcoin.csv')
df.head(30)

Date         Price
0   5/23/2019   7881.846680
1   5/24/2019   7987.371582
2   5/25/2019   8052.543945
3   5/26/2019   8673.215820
4   5/27/2019   8805.778320
5   5/28/2019   8719.961914
6   5/29/2019   8659.487305
7   5/30/2019   8319.472656
8   5/31/2019   8574.501953
9    6/1/2019   8564.016602
10   6/2/2019   8742.958008
11   6/3/2019   8208.995117
12   6/4/2019   7707.770996
13   6/5/2019   7824.231445
14   6/6/2019   7822.023438
15   6/7/2019   8043.951172
16   6/8/2019   7954.127930
17   6/9/2019   7688.077148
18  6/10/2019   8000.329590
19  6/11/2019   7927.714355
20  6/12/2019   8145.857422
21  6/13/2019   8230.923828
22  6/14/2019   8693.833008
23  6/15/2019   8838.375000
24  6/16/2019   8994.488281
25  6/17/2019   9320.352539
26  6/18/2019   9081.762695
27  6/19/2019   9273.521484
28  6/20/2019   9527.160156
29  6/21/2019  10144.556640

In [31]:
df.drop('Date',axis = 1, inplace = True)

In [32]:
predictionDays = 30

In [33]:
df['Prediction'] = df.Price.shift(-predictionDays)

In [34]:
df

Price   Prediction
0    7881.846680  10701.69141
1    7987.371582  10855.37109
2    8052.543945  11011.10254
3    8673.215820  11790.91699
4    8805.778320  13016.23145
..           ...          ...
362  9729.038086          NaN
363  9522.981445          NaN
364  9081.761719          NaN
365  9182.577148          NaN
366  9180.045898          NaN

[367 rows x 2 columns]

In [47]:
X = np.array(df.drop('Prediction', axis = 1))
len(X)

367

In [48]:
X = X[:len(X) - predictionDays]
len(X)

337

In [42]:
Y = np.array(df['Prediction'])
Y = Y[:-predictionDays]
print(Y)

[10701.69141  10855.37109  11011.10254  11790.91699  13016.23145
 11182.80664  12407.33203  11959.37109  10817.15527  10583.13477
 10801.67773  11961.26953  11215.4375   10978.45996  11208.55078
 11450.84668  12285.95801  12573.8125   12156.5127   11358.66211
 11815.98633  11392.37891  10256.05859  10895.08984   9477.641602
  9693.802734 10666.48242  10530.73242  10767.13965  10599.10547
 10343.10645   9900.767578  9811.925781  9911.841797  9870.303711
  9477.677734  9552.860352  9519.145508  9607.423828 10085.62793
 10399.66895  10518.17481  10821.72656  10970.18457  11805.65332
 11478.16895  11941.96875  11966.40723  11862.93652  11354.02441
 11523.5791   11382.61621  10895.83008  10051.7041   10311.5459
 10374.33887  10231.74414  10345.81055  10916.05371  10763.23242
 10138.04981  10131.05566  10407.96484  10159.96094  10138.51758
 10370.82031  10185.5       9754.422852  9510.200195  9598.173828
  9630.664063  9757.970703 10346.76074  10623.54004  10594.49316
 10575.5332   10353.302

In [44]:
from sklearn.model_selection import train_test_split

In [49]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [50]:
pred_days = np.array(df.drop('Prediction', axis = 1))[-predictionDays:]
print(pred_days)

[[7550.900879]
 [7569.936035]
 [7679.867188]
 [7795.601074]
 [7807.058594]
 [8801.038086]
 [8658.553711]
 [8864.766602]
 [8988.59668 ]
 [8897.46875 ]
 [8912.654297]
 [9003.070313]
 [9268.761719]
 [9951.518555]
 [9842.666016]
 [9593.896484]
 [8756.430664]
 [8601.795898]
 [8804.477539]
 [9269.987305]
 [9733.72168 ]
 [9328.197266]
 [9377.013672]
 [9670.739258]
 [9726.575195]
 [9729.038086]
 [9522.981445]
 [9081.761719]
 [9182.577148]
 [9180.045898]]


In [51]:
from sklearn.svm import SVR

In [59]:
model = SVR(kernel = 'rbf', gamma = 0.00001, C=1e3)

In [60]:
model.fit(x_train, y_train)

SVR(C=1000.0, gamma=1e-05)

In [66]:
model.predict(x_test)

array([ 8585.17413895,  9002.89749085,  8987.40403042,  8514.68947203,
        8478.80175701,  8639.34131896,  8071.31103041,  7642.27989949,
        8277.21545908,  8719.14233069, 10136.13499553,  9808.09235104,
        8598.07542345,  9938.02732203, 10275.98095371, 10309.93063458,
        8355.47009421,  7359.41709897,  8891.13122978,  8891.15251592,
       10205.0381743 , 10029.44945644,  8122.8117063 ,  9359.98764827,
        8443.73748641,  7544.12234268, 10207.22065305,  8600.1737734 ,
        7838.42902295,  8481.54638546,  9419.016406  ,  9499.72837128,
       10027.09201997,  7977.80433378,  8573.30381115,  8800.56520327,
        9126.57277822,  7927.32934916,  8372.56040106,  8950.07640875,
        8983.51689318,  8029.29001548, 10207.54024707,  8702.06191448,
        8772.56958103,  9844.31453124, 10068.02020079, 10063.885598  ,
        8190.71263819,  9937.77357057,  7928.60474249,  8250.16826195,
        8537.30884187, 10044.07942314, 10529.10347892, 10083.66175733,
      

In [62]:
y_test

array([ 9754.422852,  8807.010742,  8988.59668 , 11182.80664 ,
        9316.629883,  8078.203125,  8251.845703,  8820.522461,
       10895.83008 , 11215.4375  , 11478.16895 ,  9244.972656,
        8245.915039,  7642.75    ,  9607.423828, 10916.05371 ,
        9510.200195,  9477.641602,  7569.936035,  9670.739258,
       10231.74414 , 11450.84668 , 10374.33887 ,  9256.148438,
        8321.005859,  6881.958496, 10410.12695 ,  9726.575195,
        7410.656738,  8869.669922,  9267.561523,  9235.354492,
       10115.97559 ,  8801.038086,  7463.105957,  6429.841797,
        9055.526367, 10530.73242 ,  6733.387207,  9663.181641,
        8804.477539, 10214.37988 , 10623.54004 ,  9633.386719,
        7493.48877 ,  7176.414551,  6865.493164,  7302.089355,
        6416.314941, 11862.93652 ,  9358.589844,  7911.430176,
        8929.038086,  9856.611328,  9477.677734, 10575.5332  ,
        8047.526855,  8104.185547,  8205.939453,  6242.193848,
        8309.286133,  9900.767578,  8550.760742,  9392.

In [72]:
df.tail(30)

Price  Prediction
337  7550.900879         NaN
338  7569.936035         NaN
339  7679.867188         NaN
340  7795.601074         NaN
341  7807.058594         NaN
342  8801.038086         NaN
343  8658.553711         NaN
344  8864.766602         NaN
345  8988.596680         NaN
346  8897.468750         NaN
347  8912.654297         NaN
348  9003.070313         NaN
349  9268.761719         NaN
350  9951.518555         NaN
351  9842.666016         NaN
352  9593.896484         NaN
353  8756.430664         NaN
354  8601.795898         NaN
355  8804.477539         NaN
356  9269.987305         NaN
357  9733.721680         NaN
358  9328.197266         NaN
359  9377.013672         NaN
360  9670.739258         NaN
361  9726.575195         NaN
362  9729.038086         NaN
363  9522.981445         NaN
364  9081.761719         NaN
365  9182.577148         NaN
366  9180.045898         NaN

In [75]:
print("Prediction for the next 30 days")
print()
prediction = model.predict(pred_days)
for i in prediction:
    print(i)

Prediction for the next 30 days

7757.6030527797075
7807.321806427428
8478.538804039843
9470.633809714438
9555.983249218523
8160.5840769154265
8699.954792921293
7847.850596199449
7373.255819027535
7695.97377786118
7630.305250352417
7341.055567043246
7902.417348079975
8536.9630885829
8210.592861953075
8397.7359853093
8367.412829552834
8797.895895887663
8143.858730609925
7908.822403617377
8075.000376695088
8209.929668739309
8425.489771892908
8171.862451676812
8079.721317387562
8077.8972475019
8578.839561928256
7280.556510355105
7502.235830042577
7492.83360662388
