In [1]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits
import numpy as np

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.2)

In [5]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/home/charles/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9583333333333334

In [6]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

In [7]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9694444444444444

In [8]:
from sklearn.model_selection import KFold

In [9]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

/home/charles/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9583333333333334

In [13]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9777777777777777

In [21]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9861111111111112

In [14]:
from sklearn.model_selection import StratifiedKFold

In [24]:
folds = StratifiedKFold(n_splits=3)

In [25]:
l_score = []
s_score = []
r_score = []

for train_index, test_index in kf.split(digits.data):
    X_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]
    l_score.append(get_score(LogisticRegression(), X_train, x_test, y_train, y_test))
    s_score.append(get_score(SVC(), X_train, x_test, y_train, y_test))
    r_score.append(get_score(RandomForestClassifier(), X_train, x_test, y_train, y_test))

/home/charles/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/charles/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regressi

In [26]:
l_score

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [27]:
s_score

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [28]:
r_score

[0.9382303839732888, 0.9515859766277128, 0.9265442404006677]