In [2]:
from sklearn import linear_model 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('MVhomeprices.txt')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
x = df['bedrooms'].median()
x

4.0

In [5]:
df.fillna(x, inplace = True)

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.corr()

area  bedrooms       age     price
area      1.000000  0.751710 -0.445300  0.901476
bedrooms  0.751710  1.000000 -0.877221  0.919803
age      -0.445300 -0.877221  1.000000 -0.734167
price     0.901476  0.919803 -0.734167  1.000000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price) #train your linear regression model - fit()

LinearRegression()

In [9]:
print(reg.predict([[10000, 6, 100]]))

[1159108.91089109]


/home/charles/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540396

## Hiring

In [36]:
data = pd.read_csv('hiring.csv')
data

experience  test_score(out of 10)  interview_score(out of 10)  salary
0         NaN                    8.0                           9   50000
1         NaN                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    NaN                           7   72000
7        11.0                    7.0                           8   80000

In [37]:
x = data['test_score(out of 10)'].mean()
x

7.857142857142857

In [38]:
data['test_score(out of 10)'].fillna(x, inplace = True)

In [39]:
data['experience'].fillna(0, inplace = True)

In [40]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary
0         0.0               8.000000                           9   50000
1         0.0               8.000000                           6   45000
2         5.0               6.000000                           7   60000
3         2.0              10.000000                          10   65000
4         7.0               9.000000                           6   70000
5         3.0               7.000000                          10   62000
6        10.0               7.857143                           7   72000
7        11.0               7.000000                           8   80000

In [41]:
reg = linear_model.LinearRegression()
reg.fit(data[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], data.salary)

LinearRegression()

In [42]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [43]:
reg.intercept_

17237.330313727158

## Predicting 

* 2 years experience 9 test_score 6 interview_score
* 12 years experience 10 test_score 10 interview_score

In [44]:
reg.predict([[2,9,6]])

/home/charles/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

In [45]:
reg.predict([[12, 10, 10]])

/home/charles/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])